name: Build and Deploy with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Using Adoptium's Temurin

      - name: Make Gradle Wrapper Executable (Linux/MacOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew  # Ensures gradlew has execute permissions on non-Windows platforms

      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Deploying build to AWS CodeDeploy..."
